services:
  - type: web
    name: fastapi-ml
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash src/api/start.sh"
    repo: https://github.com/Bfestus/Student-Retention.git
    branch: main
    healthCheckPath: "/docs"
    envVars:
      - key: PORT
        value: 10000
